# site settings
title: Алкотур
subtitle: 'Где пить в Питере'
email: 
description: выпить в баре
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: улица ад
city: город блин
state: пиздец
zip_code: 69
country: сука блять
phone: 69 69 69 69

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:

facebook_url: https://facebook.com
vkontakte_url:  https://vk.com
twitter_url: https://twitter.com
instagram_url: https://instagram.com
youtube_url: https://youtube.com
youtube_channel_url: https://youtube.com

github_url:
gitlab_url: 
googleplus_url: 
linkedin_url: 
pinterest_url:
slack_url:



# build settings
markdown: kramdown

sass:
  style: compressed
